In [2]:
import os

In [3]:
%pwd

'c:\\Users\\as296\\Desktop\\DevSphere-Tasks\\Movie-Review-sentiment-classification\\Experiments'

In [4]:
os.chdir("../")

In [5]:
%pwd

'c:\\Users\\as296\\Desktop\\DevSphere-Tasks\\Movie-Review-sentiment-classification'

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("IMDB Dataset.csv")

In [8]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
df.shape

(50000, 2)

In [12]:
df.isna().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [11]:
text1 = df['review'][1]

In [12]:
print(text1)

A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.

In [13]:
import re

text11 = re.sub("<br /><br />","", text1)

In [14]:
re.sub(r'[^a-zA-Z0-9.\'\s]', '', text11)

"A wonderful little production. The filming technique is very unassuming very oldtimeBBC fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece. The actors are extremely well chosen Michael Sheen not only has got all the polari but he has all the voices down pat too You can truly see the seamless editing guided by the references to Williams' diary entries not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. The realism really comes home with the little things the fantasy of the guard which rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses particularly with the scenes concerning Orton and Halliwell and the sets particularly of their flat with Halliwell's murals decorating every surface are terribly well done."

In [15]:
def preprocess_data(text):
    text1 = re.sub("<br /><br />","", text)
    text2 = re.sub(r'[^a-zA-Z0-9.\'\s]', '', text1)

    return text2

In [16]:
preprocess_data(text1)

"A wonderful little production. The filming technique is very unassuming very oldtimeBBC fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece. The actors are extremely well chosen Michael Sheen not only has got all the polari but he has all the voices down pat too You can truly see the seamless editing guided by the references to Williams' diary entries not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. The realism really comes home with the little things the fantasy of the guard which rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses particularly with the scenes concerning Orton and Halliwell and the sets particularly of their flat with Halliwell's murals decorating every surface are terribly well done."

In [17]:
df['Review'] = df['review'].map(lambda x: preprocess_data(x))

In [18]:
df['Review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's Love in the Time of Money is a...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: Review, Length: 50000, dtype: object

In [19]:
df

,review,sentiment,Review
0,One of the other reviewers has mentioned that ...,positive,One of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,positive,A wonderful little production. The filming tec...
2,I thought this was a wonderful way to spend ti...,positive,I thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,negative,Basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,Petter Mattei's Love in the Time of Money is a...
...,...,...,...
49995,I thought this movie did a down right good job...,positive,I thought this movie did a down right good job...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,Bad plot bad dialogue bad acting idiotic direc...
49997,I am a Catholic taught in parochial elementary...,negative,I am a Catholic taught in parochial elementary...
49998,I'm going to have to disagree with the previou...,negative,I'm going to have to disagree with the previou...
49999,No one expects the Star Trek movies to be high...,negative,No one expects the Star Trek movies to be high...

In [20]:
df.drop(columns=['review'], axis=1, inplace=True)

In [21]:
df

      sentiment                                             Review
0      positive  One of the other reviewers has mentioned that ...
1      positive  A wonderful little production. The filming tec...
2      positive  I thought this was a wonderful way to spend ti...
3      negative  Basically there's a family where a little boy ...
4      positive  Petter Mattei's Love in the Time of Money is a...
...         ...                                                ...
49995  positive  I thought this movie did a down right good job...
49996  negative  Bad plot bad dialogue bad acting idiotic direc...
49997  negative  I am a Catholic taught in parochial elementary...
49998  negative  I'm going to have to disagree with the previou...
49999  negative  No one expects the Star Trek movies to be high...

[50000 rows x 2 columns]

In [27]:
df[['Review', 'sentiment']] = df[['sentiment', 'Review']].values

In [28]:
df

                                               sentiment    Review
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's Love in the Time of Money is a...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot bad dialogue bad acting idiotic direc...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [29]:
%mkdir data

In [30]:
df.to_csv("data/dataReviews.csv")